# -*- coding: utf-8 -*-
"""All visible copy for AMP Insurance Assistance, in English and Spanish.

Edit text here, then run:  python _src/build.py
Keys used by the shared script (site.js) live in COMMON. Each page adds its own keys.
"""

BRAND = "AMP Insurance Assistance"
OWNER = "Ana María Palacios"
BROKER = "AGB Insurance"
TRAVEL_PARTNER = "Best Travel Assistance"

# ---------------------------------------------------------------- COMMON
COMMON = {
 "en": {
  "skip": "Skip to content",
  "brand_sub": "Ana María Palacios",
  "nav_auto": "Auto", "nav_home": "Home", "nav_renters": "Renters", "nav_travel": "Travel", "nav_business": "Business",
  "nav_home_page": "Home page",
  "menu_open": "Open menu", "menu_close": "Close menu",
  "cta_quote": "Get a quote", "cta_whatsapp": "Chat on WhatsApp",
  "remove": "Remove",
  "opt": "(optional)",
  # form
  "q_type": "What do you want to insure?",
  "q_details": "Your details",
  "q_contact": "How to reach you",
  "t_auto": "Auto", "t_home": "Home", "t_renters": "Renters", "t_travel": "Travel", "t_business": "Business",
  "err_type": "Choose the type of insurance you want to quote.",
  "err_required": "Fill in this field.",
  "err_zip": "Enter a 5-digit ZIP code.",
  "err_year": "Enter a 4-digit year.",
  "err_email": "Enter a valid email.",
  "err_dob": "Enter a date of birth.",
  "err_dob_future": "Date of birth cannot be in the future.",
  "err_ret": "Return date must be after departure.",
  "err_name": "Enter the full name.",
  "err_choose": "Choose one option.",
  "err_consent": "Check this box so I can contact you.",
  "f_name": "Full name", "ph_name": "First and last name", "f_dob": "Date of birth",
  "f_zip": "ZIP code", "ph_zip": "5 digits",
  "f_current": "Current insurance company",
  # auto
  "a_zip": "ZIP code where the car is kept",
  "driver": "Driver", "add_driver": "Add another driver",
  "vehicle": "Vehicle", "add_vehicle": "Add another vehicle",
  "f_year": "Year", "f_make": "Make", "ph_make": "Toyota", "f_model": "Model", "ph_model": "Corolla",
  "a_cov": "Coverage you want", "a_cov_min": "State minimum", "a_cov_full": "Full coverage", "a_cov_unsure": "Not sure",
  # home
  "h_ptype": "Type of property", "h_house": "House", "h_condo": "Condo", "h_town": "Townhouse", "h_mobile": "Mobile home", "h_rental": "Rental property I own",
  "h_zip": "ZIP code of the property", "h_built": "Year built",
  "h_owner": "Owner's full name", "h_owner_dob": "Owner's date of birth",
  "h_extra": "Also quote", "h_flood": "Flood", "h_umbrella": "Umbrella",
  # renters
  "r_zip": "ZIP code of your rental", "r_name": "Your full name", "r_dob": "Your date of birth",
  "r_move": "Move-in date", "r_value": "About how much are your belongings worth?",
  "r_v1": "Under $15,000", "r_v2": "$15,000 to $30,000", "r_v3": "$30,000 to $50,000", "r_v4": "Over $50,000", "r_v5": "Not sure",
  # travel
  "traveler": "Traveler", "add_traveler": "Add another traveler",
  "tr_from": "Leaving from", "tr_to": "Going to", "ph_city": "City or country",
  "tr_res": "Country where you live", "ph_country": "Country",
  "tr_dep": "Departure", "tr_ret": "Return",
  "tr_purpose": "Trip purpose", "p_vacation": "Vacation", "p_business": "Business", "p_study": "Study", "p_family": "Visiting family",
  "tr_prio": "Coverage you care about", "c_medical": "Medical", "c_cancel": "Cancellation", "c_baggage": "Baggage", "c_delays": "Delays",
  # business
  "b_name": "Business name", "b_what": "What does the business do?", "ph_what": "Example: cleaning, restaurant",
  "b_zip": "Business ZIP code", "b_owner": "Your full name",
  "b_years": "Years in business", "b_emps": "Number of employees",
  "b_cov": "Coverage you need", "b_gl": "General liability", "b_prop": "Commercial property", "b_auto": "Commercial auto",
  "b_wc": "Workers' comp", "b_pro": "Professional liability", "b_unsure": "Not sure",
  # contact
  "f_wa": "WhatsApp number", "f_email": "Email",
  "consent": "I agree to send these details to Ana María Palacios on WhatsApp so she, or a licensed agent at her agency, can prepare my quote and contact me about it.",
  "consent_link": "Read the Privacy Policy",
  "submit": "Send on WhatsApp",
  "form_note": "WhatsApp opens with your message ready to review. Nothing is sent until you tap send. Please do not include driver's license numbers, VINs, Social Security numbers, health details, or passport numbers.",
  "s_h": "One more tap",
  "s_p": "WhatsApp should open with your request. Tap send there so it reaches me. If it did not open, use the button below.",
  "s_open": "Open WhatsApp", "s_copy": "Copy details", "s_copied": "Copied", "s_edit": "Edit",
  # WhatsApp message labels
  "wa_greeting": "Hi Ana! I would like an insurance quote.",
  "wa_title_auto": "New auto insurance quote request", "wa_title_home": "New home insurance quote request",
  "wa_title_renters": "New renters insurance quote request", "wa_title_travel": "New travel insurance quote request",
  "wa_title_business": "New business insurance quote request",
  "wa_age": "age", "wa_dob": "DOB",
  "wa_zip": "ZIP code", "wa_drivers": "Drivers", "wa_vehicles": "Vehicles", "wa_cov": "Coverage", "wa_current": "Current insurer",
  "wa_ptype": "Property type", "wa_built": "Year built", "wa_owner": "Owner", "wa_owner_dob": "Owner DOB", "wa_extra": "Also quote",
  "wa_name": "Name", "wa_move": "Move-in date", "wa_value": "Belongings value",
  "wa_travelers": "Travelers", "wa_from": "Leaving from", "wa_to": "Going to", "wa_res": "Country of residence",
  "wa_dep": "Departure", "wa_ret": "Return", "wa_purpose": "Trip purpose", "wa_prio": "Coverage priorities",
  "wa_bname": "Business", "wa_bwhat": "What it does", "wa_years": "Years in business", "wa_emps": "Employees", "wa_bcov": "Coverage needed",
  "wa_contact_wa": "WhatsApp", "wa_contact_email": "Email",
  # quote section
  "quote_eyebrow": "Free quote",
  "quote_h2": "Request a quote",
  "quote_sub": "Choose the type of insurance, answer a few questions, and WhatsApp opens with your details ready to send.",
  "assure_1": "I read and answer your request myself.",
  "assure_2": "Your details go only to me and my agency.",
  "assure_3": "No account and no long forms.",
  # trust band
  "broker_t": "Policies through AGB Insurance",
  "broker_p": "The independent insurance agency Ana works with",
  "travel_t": "Travel plans through Best Travel Assistance",
  "travel_p": "Ana's travel insurance partner",
  "fact_1": "You talk to me, not a call center",
  "fact_2": "Free quotes with no obligation",
  "fact_3": "Help in English and Spanish",
  # footer
  "foot_tag": "Auto, home, renters, travel, and business insurance help in English and Spanish.",
  "foot_contact": "Contact", "foot_ins": "Insurance", "foot_legal_h": "Legal",
  "l_privacy": "Privacy Policy", "l_terms": "Terms and Conditions", "l_cookies": "Cookie Policy", "l_refund": "Refund Policy",
  "foot_legal": "AMP Insurance Assistance is the insurance service of Ana María Palacios. Ana is a licensed travel insurance agent, and travel plans are offered through Best Travel Assistance. For auto, home, renters, and business insurance, Ana acts as your advisor, and a licensed agent at AGB Insurance prepares your quote and issues your policy. Your policy documents set out your coverage, exclusions, price, and the company responsible for paying claims, and they control over anything on this site. This site gives general information only. It is not an insurance contract, and a quote does not guarantee eligibility or coverage.",
  "faq_more": "Still have a question?",
  "faq_h2": "Questions and answers",
  "learn_more": "Learn more",
  "back_home": "All insurance types",
  "cov_fine": "Coverage, limits, deductibles, and exclusions depend on the policy you choose.",
  "more_h": "Other insurance I can help with",
  "adv_h": "How I help with this insurance",
  "adv_p": "I am your advisor for this type of insurance. I gather your details, explain your options in plain words, and connect you with a licensed agent at AGB Insurance, who prepares your quote and issues your policy. You keep talking to me the whole time.",
  "agent_h": "I am your travel insurance agent",
  "agent_p": "I am licensed to sell travel insurance, and my travel plans come through Best Travel Assistance. I prepare your quote, explain each plan, and help you buy it, all in the same WhatsApp chat.",
 },
 "es": {
  "skip": "Saltar al contenido",
  "brand_sub": "Ana María Palacios",
  "nav_auto": "Auto", "nav_home": "Hogar", "nav_renters": "Inquilinos", "nav_travel": "Viaje", "nav_business": "Negocios",
  "nav_home_page": "Inicio",
  "menu_open": "Abrir menú", "menu_close": "Cerrar menú",
  "cta_quote": "Cotizar", "cta_whatsapp": "Escríbeme por WhatsApp",
  "remove": "Quitar",
  "opt": "(opcional)",
  "q_type": "¿Qué quieres asegurar?",
  "q_details": "Tus datos",
  "q_contact": "Cómo contactarte",
  "t_auto": "Auto", "t_home": "Hogar", "t_renters": "Inquilinos", "t_travel": "Viaje", "t_business": "Negocio",
  "err_type": "Elige el tipo de seguro que quieres cotizar.",
  "err_required": "Completa este campo.",
  "err_zip": "Escribe un código postal de 5 dígitos.",
  "err_year": "Escribe un año de 4 dígitos.",
  "err_email": "Escribe un correo válido.",
  "err_dob": "Escribe una fecha de nacimiento.",
  "err_dob_future": "La fecha de nacimiento no puede ser futura.",
  "err_ret": "La fecha de regreso debe ser posterior a la salida.",
  "err_name": "Escribe el nombre completo.",
  "err_choose": "Elige una opción.",
  "err_consent": "Marca esta casilla para que pueda contactarte.",
  "f_name": "Nombre completo", "ph_name": "Nombre y apellido", "f_dob": "Fecha de nacimiento",
  "f_zip": "Código postal", "ph_zip": "5 dígitos",
  "f_current": "Compañía de seguros actual",
  "a_zip": "Código postal donde se guarda el auto",
  "driver": "Conductor", "add_driver": "Agregar otro conductor",
  "vehicle": "Vehículo", "add_vehicle": "Agregar otro vehículo",
  "f_year": "Año", "f_make": "Marca", "ph_make": "Toyota", "f_model": "Modelo", "ph_model": "Corolla",
  "a_cov": "Cobertura que quieres", "a_cov_min": "Mínimo del estado", "a_cov_full": "Cobertura completa", "a_cov_unsure": "No estoy seguro",
  "h_ptype": "Tipo de propiedad", "h_house": "Casa", "h_condo": "Condominio", "h_town": "Townhouse", "h_mobile": "Casa móvil", "h_rental": "Propiedad que alquilo",
  "h_zip": "Código postal de la propiedad", "h_built": "Año de construcción",
  "h_owner": "Nombre completo del dueño", "h_owner_dob": "Fecha de nacimiento del dueño",
  "h_extra": "Cotizar también", "h_flood": "Inundación", "h_umbrella": "Umbrella (responsabilidad extra)",
  "r_zip": "Código postal de tu alquiler", "r_name": "Tu nombre completo", "r_dob": "Tu fecha de nacimiento",
  "r_move": "Fecha de mudanza", "r_value": "¿Cuánto valen tus pertenencias, más o menos?",
  "r_v1": "Menos de $15,000", "r_v2": "$15,000 a $30,000", "r_v3": "$30,000 a $50,000", "r_v4": "Más de $50,000", "r_v5": "No estoy seguro",
  "traveler": "Viajero", "add_traveler": "Agregar otro viajero",
  "tr_from": "Sales desde", "tr_to": "Vas a", "ph_city": "Ciudad o país",
  "tr_res": "País donde vives", "ph_country": "País",
  "tr_dep": "Salida", "tr_ret": "Regreso",
  "tr_purpose": "Motivo del viaje", "p_vacation": "Vacaciones", "p_business": "Negocios", "p_study": "Estudios", "p_family": "Visitar familia",
  "tr_prio": "Cobertura que te importa", "c_medical": "Médica", "c_cancel": "Cancelación", "c_baggage": "Equipaje", "c_delays": "Demoras",
  "b_name": "Nombre del negocio", "b_what": "¿A qué se dedica el negocio?", "ph_what": "Ej.: limpieza, restaurante",
  "b_zip": "Código postal del negocio", "b_owner": "Tu nombre completo",
  "b_years": "Años en operación", "b_emps": "Número de empleados",
  "b_cov": "Cobertura que necesitas", "b_gl": "Responsabilidad civil general", "b_prop": "Propiedad comercial", "b_auto": "Auto comercial",
  "b_wc": "Compensación laboral", "b_pro": "Responsabilidad profesional", "b_unsure": "No estoy seguro",
  "f_wa": "Número de WhatsApp", "f_email": "Correo",
  "consent": "Acepto enviar estos datos a Ana María Palacios por WhatsApp para que ella, o un agente con licencia de su agencia, prepare mi cotización y me contacte sobre ella.",
  "consent_link": "Lee la Política de privacidad",
  "submit": "Enviar por WhatsApp",
  "form_note": "WhatsApp se abre con tu mensaje listo para revisar. No se envía nada hasta que toques enviar. Por favor no incluyas números de licencia de conducir, VIN, Seguro Social, datos de salud ni números de pasaporte.",
  "s_h": "Un toque más",
  "s_p": "WhatsApp debería abrirse con tu solicitud. Toca enviar allí para que me llegue. Si no se abrió, usa el botón de abajo.",
  "s_open": "Abrir WhatsApp", "s_copy": "Copiar datos", "s_copied": "Copiado", "s_edit": "Editar",
  "wa_greeting": "¡Hola Ana! Me gustaría una cotización de seguro.",
  "wa_title_auto": "Nueva solicitud de cotización de seguro de auto", "wa_title_home": "Nueva solicitud de cotización de seguro de hogar",
  "wa_title_renters": "Nueva solicitud de cotización de seguro de inquilinos", "wa_title_travel": "Nueva solicitud de cotización de seguro de viaje",
  "wa_title_business": "Nueva solicitud de cotización de seguro de negocio",
  "wa_age": "edad", "wa_dob": "Nacimiento",
  "wa_zip": "Código postal", "wa_drivers": "Conductores", "wa_vehicles": "Vehículos", "wa_cov": "Cobertura", "wa_current": "Aseguradora actual",
  "wa_ptype": "Tipo de propiedad", "wa_built": "Año de construcción", "wa_owner": "Dueño", "wa_owner_dob": "Nacimiento del dueño", "wa_extra": "Cotizar también",
  "wa_name": "Nombre", "wa_move": "Fecha de mudanza", "wa_value": "Valor de pertenencias",
  "wa_travelers": "Viajeros", "wa_from": "Sale desde", "wa_to": "Va a", "wa_res": "País de residencia",
  "wa_dep": "Salida", "wa_ret": "Regreso", "wa_purpose": "Motivo del viaje", "wa_prio": "Cobertura prioritaria",
  "wa_bname": "Negocio", "wa_bwhat": "A qué se dedica", "wa_years": "Años en operación", "wa_emps": "Empleados", "wa_bcov": "Cobertura necesaria",
  "wa_contact_wa": "WhatsApp", "wa_contact_email": "Correo",
  "quote_eyebrow": "Cotización gratis",
  "quote_h2": "Pide tu cotización",
  "quote_sub": "Elige el tipo de seguro, responde unas preguntas y WhatsApp se abre con tus datos listos para enviar.",
  "assure_1": "Leo y respondo tu solicitud personalmente.",
  "assure_2": "Tus datos llegan solo a mí y a mi agencia.",
  "assure_3": "Sin cuentas ni formularios largos.",
  "broker_t": "Pólizas a través de AGB Insurance",
  "broker_p": "La agencia de seguros independiente con la que trabaja Ana",
  "travel_t": "Planes de viaje a través de Best Travel Assistance",
  "travel_p": "La aliada de Ana en seguros de viaje",
  "fact_1": "Hablas conmigo, no con un call center",
  "fact_2": "Cotización gratis y sin compromiso",
  "fact_3": "Atención en español e inglés",
  "foot_tag": "Ayuda con seguros de auto, hogar, inquilinos, viaje y negocios en español e inglés.",
  "foot_contact": "Contacto", "foot_ins": "Seguros", "foot_legal_h": "Legal",
  "l_privacy": "Política de privacidad", "l_terms": "Términos y condiciones", "l_cookies": "Política de cookies", "l_refund": "Política de reembolsos",
  "foot_legal": "AMP Insurance Assistance es el servicio de seguros de Ana María Palacios. Ana es agente con licencia de seguros de viaje, y los planes de viaje se ofrecen a través de Best Travel Assistance. Para seguros de auto, hogar, inquilinos y negocios, Ana es tu asesora, y un agente con licencia de AGB Insurance prepara tu cotización y emite tu póliza. Los documentos de tu póliza definen tu cobertura, exclusiones, precio y la compañía responsable de pagar los reclamos, y prevalecen sobre cualquier contenido de este sitio. Este sitio es solo informativo. No es un contrato de seguro, y una cotización no garantiza elegibilidad ni cobertura.",
  "faq_more": "¿Te queda alguna duda?",
  "faq_h2": "Preguntas y respuestas",
  "learn_more": "Ver más",
  "back_home": "Todos los seguros",
  "cov_fine": "La cobertura, los límites, los deducibles y las exclusiones dependen de la póliza que elijas.",
  "more_h": "Otros seguros con los que te ayudo",
  "adv_h": "Cómo te ayudo con este seguro",
  "adv_p": "Soy tu asesora para este tipo de seguro. Reúno tus datos, te explico tus opciones en palabras claras y te conecto con un agente con licencia de AGB Insurance, que prepara tu cotización y emite tu póliza. Sigues hablando conmigo todo el tiempo.",
  "agent_h": "Soy tu agente de seguros de viaje",
  "agent_p": "Tengo licencia para vender seguros de viaje, y mis planes de viaje vienen de Best Travel Assistance. Preparo tu cotización, te explico cada plan y te ayudo a comprarlo, todo en el mismo chat de WhatsApp.",
 },
}

# ---------------------------------------------------------------- LINES (insurance types)
LINES = ["auto", "home", "renters", "travel", "business"]
LINE_URL = {"auto": "auto-insurance.html", "home": "home-insurance.html", "renters": "renters-insurance.html",
            "travel": "travel-insurance.html", "business": "business-insurance.html"}
LINE_ICON = {"auto": "car-profile", "home": "house-line", "renters": "key", "travel": "airplane-tilt", "business": "storefront"}
LINE_IMG = {"auto": "assets/line-auto.jpg", "home": "assets/line-home.jpg", "renters": "assets/line-renters.jpg",
            "travel": "assets/line-travel.jpg", "business": "assets/line-business.jpg"}

CARD = {
 "en": {
  "auto": ("Auto", "Cars and motorcycles. Liability, full coverage, and more."),
  "home": ("Home and property", "Houses, condos, and property you rent out. Ask about flood too."),
  "renters": ("Renters", "Your belongings and liability when you rent your home."),
  "travel": ("Travel", "Medical, cancellation, and baggage coverage for your trips."),
  "business": ("Business", "Liability, property, commercial auto, and workers' comp."),
 },
 "es": {
  "auto": ("Auto", "Autos y motos. Responsabilidad civil, cobertura completa y más."),
  "home": ("Hogar y propiedad", "Casas, condominios y propiedades que alquilas. Pregunta también por inundación."),
  "renters": ("Inquilinos", "Tus pertenencias y tu responsabilidad civil cuando alquilas."),
  "travel": ("Viaje", "Cobertura médica, de cancelación y de equipaje para tus viajes."),
  "business": ("Negocios", "Responsabilidad civil, propiedad, autos comerciales y compensación laboral."),
 },
}

# ---------------------------------------------------------------- HOME PAGE
HOME = {
 "file": "index.html",
 "meta": {
  "en": ("AMP Insurance Assistance | Auto, Home, Renters, Travel & Business Insurance in English and Spanish",
         "Ana María Palacios helps you quote auto, home, renters, travel, and business insurance in English and Spanish. Send your details by WhatsApp."),
  "es": ("AMP Insurance Assistance | Seguros de auto, hogar, inquilinos, viaje y negocios en español",
         "Ana María Palacios te ayuda a cotizar seguros de auto, hogar, inquilinos, viaje y negocios en español e inglés. Envía tus datos por WhatsApp."),
 },
 "en": {
  "hero_eyebrow": "Insurance help in English and Spanish",
  "hero_h1": "All your insurance in <em>one WhatsApp chat.</em>",
  "hero_sub": "Auto, home, renters, travel, and business insurance. Tell me what you need and I will get you options.",
  "hero_role": "AMP Insurance Assistance",
  "lines_h2": "What can I help you insure?",
  "lines_sub": "Pick a type of insurance to learn more, or go straight to a quote.",
  "how_h2": "Covered in three steps",
  "how_1_t": "Tell me what you need", "how_1_d": "Fill in the short quote form below. It takes a few minutes.",
  "how_2_t": "Compare your options", "how_2_d": "You get options and prices on WhatsApp.",
  "how_3_t": "Get covered", "how_3_d": "Pick a policy and I help you finish the purchase.",
  "about_h2": "Hi, I am Ana María",
  "about_p1": "I help families and business owners find insurance that fits their needs and budget, in English or Spanish. I know the questions people forget to ask and the details that count when something goes wrong.",
  "about_p2": "When you message me, you talk to me. I explain your options in plain words and help you after you buy, too.",
  "faq": [
   {"q": "Which types of insurance can you quote?", "a": "Auto, home and property, renters, travel, and business insurance. I do not offer life or health insurance."},
   {"q": "How does a WhatsApp quote work?", "a": "Fill in the quote form or message me directly. I review what you need and send options in the chat. You ask questions, pick a policy if you want one, and I help with the next steps."},
   {"q": "Is there any cost to get a quote?", "a": "No. Quotes and guidance are free with no obligation."},
   {"q": "Are you my agent or my advisor?", "a": "For travel insurance, I am your agent, and plans come through Best Travel Assistance. For auto, home, renters, and business insurance, I am your advisor: I gather your details and explain your options, and a licensed agent at AGB Insurance prepares your quote and issues your policy. You keep talking to me the whole time."},
   {"q": "Do you help in Spanish?", "a": "Yes. I help you fully in English and Spanish."},
   {"q": "What information should I not send?", "a": "Please do not send driver's license numbers, VINs, Social Security numbers, health details, passport numbers, or payment information through the form. If a quote needs any of these, I will ask for it in our chat."},
  ],
 },
 "es": {
  "hero_eyebrow": "Seguros en español e inglés",
  "hero_h1": "Todos tus seguros en <em>un chat de WhatsApp.</em>",
  "hero_sub": "Seguros de auto, hogar, inquilinos, viaje y negocios. Cuéntame qué necesitas y te consigo opciones.",
  "hero_role": "AMP Insurance Assistance",
  "lines_h2": "¿Qué quieres asegurar?",
  "lines_sub": "Elige un tipo de seguro para ver más, o ve directo a la cotización.",
  "how_h2": "Cubierto en tres pasos",
  "how_1_t": "Cuéntame qué necesitas", "how_1_d": "Completa el formulario corto de abajo. Toma unos minutos.",
  "how_2_t": "Compara opciones", "how_2_d": "Recibes opciones y precios por WhatsApp.",
  "how_3_t": "Quédate cubierto", "how_3_d": "Eliges una póliza y te ayudo a completar la compra.",
  "about_h2": "Hola, soy Ana María",
  "about_p1": "Ayudo a familias y dueños de negocios a encontrar seguros que se ajusten a sus necesidades y presupuesto, en español o inglés. Conozco las preguntas que la gente olvida hacer y los detalles que cuentan cuando algo sale mal.",
  "about_p2": "Cuando me escribes, hablas conmigo. Te explico tus opciones en palabras claras y te ayudo también después de comprar.",
  "faq": [
   {"q": "¿Qué tipos de seguro puedes cotizar?", "a": "Seguros de auto, hogar y propiedad, inquilinos, viaje y negocios. No ofrezco seguros de vida ni de salud."},
   {"q": "¿Cómo funciona cotizar por WhatsApp?", "a": "Completa el formulario o escríbeme directo. Reviso lo que necesitas y te envío opciones en el chat. Preguntas lo que quieras, eliges una póliza si te conviene y te ayudo con los siguientes pasos."},
   {"q": "¿Cotizar tiene algún costo?", "a": "No. Las cotizaciones y la orientación son gratis y sin compromiso."},
   {"q": "¿Eres mi agente o mi asesora?", "a": "Para seguros de viaje, soy tu agente, y los planes vienen de Best Travel Assistance. Para seguros de auto, hogar, inquilinos y negocios, soy tu asesora: reúno tus datos y te explico tus opciones, y un agente con licencia de AGB Insurance prepara tu cotización y emite tu póliza. Sigues hablando conmigo todo el tiempo."},
   {"q": "¿Me ayudas en español?", "a": "Sí. Te atiendo por completo en español e inglés."},
   {"q": "¿Qué información no debo enviar?", "a": "Por favor no envíes por el formulario números de licencia de conducir, VIN, Seguro Social, datos de salud, números de pasaporte ni datos de pago. Si una cotización necesita alguno de ellos, te lo pediré en nuestro chat."},
  ],
 },
}

# ---------------------------------------------------------------- LINE PAGES
# Each: meta (title, description), eyebrow, h1 (may contain <em>), sub, cov_h2, items [(icon, title, text)], faq
PAGES = {
 "auto": {
  "meta": {
   "en": ("Auto Insurance Quotes in English and Spanish | AMP Insurance Assistance",
          "Quote auto insurance for your car or motorcycle with help in English and Spanish. Send your drivers and vehicles by WhatsApp."),
   "es": ("Cotiza tu seguro de auto en español | AMP Insurance Assistance",
          "Cotiza el seguro de tu auto o moto con atención en español e inglés. Envía tus conductores y vehículos por WhatsApp."),
  },
  "en": {
   "eyebrow": "Auto insurance",
   "h1": "Auto insurance quotes <em>in your language.</em>",
   "sub": "Tell me about your drivers and vehicles, and you get options and prices on WhatsApp.",
   "cov_h2": "What auto insurance can cover",
   "items": [
    ("shield-check", "Liability", "Pays for injuries and damage you cause to other people and their property, up to your limits."),
    ("car-profile", "Collision", "Helps repair or replace your car after an accident, minus your deductible."),
    ("cloud-lightning", "Comprehensive", "Covers theft, storms, flooding, fire, and other damage that is not a crash."),
    ("first-aid-kit", "Personal injury protection (PIP)", "Helps pay medical bills for you and your passengers. Florida requires it."),
    ("user-circle", "Uninsured motorist", "Protects you when the other driver has no insurance or not enough."),
    ("wrench", "Roadside help and rental car", "Optional extras for towing, flat tires, and a rental while your car is in the shop."),
   ],
   "faq": [
    {"q": "What does Florida require?", "a": "Florida requires at least $10,000 in personal injury protection (PIP) and $10,000 in property damage liability. Many drivers choose more coverage, and lenders usually require collision and comprehensive on financed cars."},
    {"q": "What do you need to quote my car?", "a": "The ZIP code where you keep the car, each driver's name and date of birth, and each vehicle's year, make, and model. If you choose a policy, we will ask for license and VIN details in our chat."},
    {"q": "Can I add more than one car or driver?", "a": "Yes. Use the add buttons in the form for up to six drivers and six vehicles."},
    {"q": "Can I quote a motorcycle?", "a": "Yes. Add it as a vehicle in the form, and we will confirm the details with you in our chat."},
   ],
  },
  "es": {
   "eyebrow": "Seguro de auto",
   "h1": "Cotiza tu seguro de auto <em>en tu idioma.</em>",
   "sub": "Cuéntame de tus conductores y vehículos, y recibes opciones y precios por WhatsApp.",
   "cov_h2": "Lo que puede cubrir un seguro de auto",
   "items": [
    ("shield-check", "Responsabilidad civil", "Paga lesiones y daños que causes a otras personas y a su propiedad, hasta tus límites."),
    ("car-profile", "Colisión", "Ayuda a reparar o reemplazar tu auto después de un accidente, menos tu deducible."),
    ("cloud-lightning", "Cobertura amplia", "Cubre robo, tormentas, inundaciones, incendio y otros daños que no son un choque."),
    ("first-aid-kit", "Protección contra lesiones personales (PIP)", "Ayuda a pagar gastos médicos tuyos y de tus pasajeros. Florida lo exige."),
    ("user-circle", "Conductor sin seguro", "Te protege cuando el otro conductor no tiene seguro o no tiene suficiente."),
    ("wrench", "Asistencia en carretera y auto de alquiler", "Extras opcionales para grúa, llantas pinchadas y un auto de alquiler mientras reparan el tuyo."),
   ],
   "faq": [
    {"q": "¿Qué exige Florida?", "a": "Florida exige al menos $10,000 de protección contra lesiones personales (PIP) y $10,000 de responsabilidad por daños a la propiedad. Muchos conductores eligen más cobertura, y los prestamistas normalmente exigen colisión y cobertura amplia en autos financiados."},
    {"q": "¿Qué necesitas para cotizar mi auto?", "a": "El código postal donde guardas el auto, el nombre y la fecha de nacimiento de cada conductor, y el año, la marca y el modelo de cada vehículo. Si eliges una póliza, te pediremos los datos de licencia y VIN en nuestro chat."},
    {"q": "¿Puedo agregar más de un auto o conductor?", "a": "Sí. Usa los botones de agregar en el formulario para hasta seis conductores y seis vehículos."},
    {"q": "¿Puedo cotizar una moto?", "a": "Sí. Agrégala como vehículo en el formulario y confirmamos los detalles contigo en nuestro chat."},
   ],
  },
 },
 "home": {
  "meta": {
   "en": ("Home Insurance Quotes in English and Spanish | AMP Insurance Assistance",
          "Quote homeowners, condo, landlord, and flood insurance with help in English and Spanish. Send your property details by WhatsApp."),
   "es": ("Cotiza tu seguro de hogar en español | AMP Insurance Assistance",
          "Cotiza seguros de casa, condominio, propiedad en alquiler e inundación con atención en español e inglés. Envía tus datos por WhatsApp."),
  },
  "en": {
   "eyebrow": "Home and property insurance",
   "h1": "Protect your home <em>and what is in it.</em>",
   "sub": "Homeowners, condo, and rental property insurance. Send a few details and get options on WhatsApp.",
   "cov_h2": "What home insurance can cover",
   "items": [
    ("house-line", "Your home's structure", "Repairs or rebuilds your home after covered damage like fire or wind."),
    ("couch", "Your belongings", "Furniture, electronics, clothes, and other things you own."),
    ("shield-check", "Liability", "Helps if someone gets hurt at your home or you damage someone else's property."),
    ("bed", "Living expenses", "Helps pay for a place to stay if covered damage forces you out of your home."),
    ("drop", "Flood", "Standard home policies do not cover flood. You can buy a separate flood policy."),
    ("key", "Rental property you own", "Landlord policies cover the building and your liability when you rent it out."),
   ],
   "faq": [
    {"q": "Does home insurance cover hurricanes?", "a": "Most Florida home policies cover wind damage from hurricanes, usually with a separate hurricane deductible. Flooding, including storm surge, is not covered without a flood policy."},
    {"q": "What do you need to quote my home?", "a": "The property type, ZIP code, the year it was built if you know it, and the owner's name and date of birth. We will ask for the full address and other details in our chat."},
    {"q": "I own a condo. What do I need?", "a": "A condo policy usually covers the inside of your unit, your belongings, and your liability. Your association's master policy covers the building's shared parts."},
    {"q": "Can you quote a home I rent out?", "a": "Yes. Choose \"Rental property I own\" in the form."},
   ],
  },
  "es": {
   "eyebrow": "Seguro de hogar y propiedad",
   "h1": "Protege tu casa <em>y lo que hay en ella.</em>",
   "sub": "Seguros para casas, condominios y propiedades en alquiler. Envía unos datos y recibe opciones por WhatsApp.",
   "cov_h2": "Lo que puede cubrir un seguro de hogar",
   "items": [
    ("house-line", "La estructura de tu casa", "Repara o reconstruye tu casa después de daños cubiertos como incendio o viento."),
    ("couch", "Tus pertenencias", "Muebles, electrónicos, ropa y otras cosas que te pertenecen."),
    ("shield-check", "Responsabilidad civil", "Te ayuda si alguien se lesiona en tu casa o si dañas la propiedad de otra persona."),
    ("bed", "Gastos de vivienda", "Ayuda a pagar dónde quedarte si un daño cubierto te obliga a salir de tu casa."),
    ("drop", "Inundación", "Las pólizas de hogar normales no cubren inundaciones. Puedes comprar una póliza de inundación aparte."),
    ("key", "Propiedad que alquilas", "Las pólizas para arrendadores cubren el edificio y tu responsabilidad civil cuando lo alquilas."),
   ],
   "faq": [
    {"q": "¿El seguro de hogar cubre huracanes?", "a": "La mayoría de las pólizas de hogar en Florida cubren daños por viento de huracanes, normalmente con un deducible de huracán aparte. Las inundaciones, incluida la marejada ciclónica, no están cubiertas sin una póliza de inundación."},
    {"q": "¿Qué necesitas para cotizar mi casa?", "a": "El tipo de propiedad, el código postal, el año de construcción si lo sabes, y el nombre y la fecha de nacimiento del dueño. Te pediremos la dirección completa y otros detalles en nuestro chat."},
    {"q": "Tengo un condominio. ¿Qué necesito?", "a": "Una póliza de condominio normalmente cubre el interior de tu unidad, tus pertenencias y tu responsabilidad civil. La póliza maestra de la asociación cubre las áreas comunes del edificio."},
    {"q": "¿Puedes cotizar una casa que alquilo?", "a": "Sí. Elige \"Propiedad que alquilo\" en el formulario."},
   ],
  },
 },
 "renters": {
  "meta": {
   "en": ("Renters Insurance Quotes in English and Spanish | AMP Insurance Assistance",
          "Quote renters insurance for your belongings and liability with help in English and Spanish. Send your details by WhatsApp."),
   "es": ("Cotiza tu seguro de inquilinos en español | AMP Insurance Assistance",
          "Cotiza un seguro de inquilinos para tus pertenencias y tu responsabilidad civil, con atención en español e inglés."),
  },
  "en": {
   "eyebrow": "Renters insurance",
   "h1": "Renters insurance <em>for your things and you.</em>",
   "sub": "Your landlord's policy covers the building, not your belongings. Renters insurance covers what is yours.",
   "cov_h2": "What renters insurance can cover",
   "items": [
    ("couch", "Your belongings", "Furniture, electronics, and clothes after theft, fire, and other covered events."),
    ("shield-check", "Liability", "Helps if a guest gets hurt in your home or you damage someone else's property by accident."),
    ("bed", "Living expenses", "Helps pay for a hotel and meals if covered damage makes your home unlivable."),
    ("suitcase-rolling", "Your things away from home", "Many policies also cover belongings stolen from your car or while you travel."),
   ],
   "faq": [
    {"q": "Does my landlord's insurance cover my things?", "a": "No. Your landlord's policy covers the building. Your belongings and your liability need your own renters policy."},
    {"q": "Can my landlord require renters insurance?", "a": "Many leases do. Check your lease and send me the requirement so the quote matches it."},
    {"q": "What do you need to quote renters insurance?", "a": "The ZIP code of your rental, your name and date of birth, and a rough value of your belongings."},
   ],
  },
  "es": {
   "eyebrow": "Seguro de inquilinos",
   "h1": "Seguro de inquilinos <em>para tus cosas y para ti.</em>",
   "sub": "La póliza del dueño cubre el edificio, no tus pertenencias. El seguro de inquilinos cubre lo tuyo.",
   "cov_h2": "Lo que puede cubrir un seguro de inquilinos",
   "items": [
    ("couch", "Tus pertenencias", "Muebles, electrónicos y ropa después de robo, incendio y otros eventos cubiertos."),
    ("shield-check", "Responsabilidad civil", "Te ayuda si un invitado se lesiona en tu casa o si dañas por accidente la propiedad de otra persona."),
    ("bed", "Gastos de vivienda", "Ayuda a pagar hotel y comidas si un daño cubierto hace que tu casa no se pueda habitar."),
    ("suitcase-rolling", "Tus cosas fuera de casa", "Muchas pólizas también cubren pertenencias robadas de tu auto o mientras viajas."),
   ],
   "faq": [
    {"q": "¿El seguro del dueño cubre mis cosas?", "a": "No. La póliza del dueño cubre el edificio. Tus pertenencias y tu responsabilidad civil necesitan tu propia póliza de inquilinos."},
    {"q": "¿El dueño puede exigirme un seguro de inquilinos?", "a": "Muchos contratos de alquiler lo exigen. Revisa tu contrato y envíame el requisito para que la cotización lo cumpla."},
    {"q": "¿Qué necesitas para cotizar un seguro de inquilinos?", "a": "El código postal de tu alquiler, tu nombre y fecha de nacimiento, y un valor aproximado de tus pertenencias."},
   ],
  },
 },
 "travel": {
  "meta": {
   "en": ("Travel Insurance Quotes in English and Spanish | AMP Insurance Assistance",
          "Quote travel insurance for medical care, cancellation, delays, and baggage with help in English and Spanish. Send your trip by WhatsApp."),
   "es": ("Cotiza tu seguro de viaje en español | AMP Insurance Assistance",
          "Cotiza un seguro de viaje con cobertura médica, de cancelación, demoras y equipaje, con atención en español e inglés."),
  },
  "en": {
   "eyebrow": "Travel insurance",
   "h1": "Travel insurance <em>for your next trip.</em>",
   "sub": "Tell me who is traveling and where. I will send plan options that fit your trip and budget.",
   "cov_h2": "What travel insurance can cover",
   "items": [
    ("first-aid-kit", "Emergency medical care", "Help with medical costs if you get sick or hurt while you are away."),
    ("calendar-x", "Trip cancellation", "Reimbursement of prepaid costs when a covered reason stops your trip."),
    ("clock-countdown", "Delays and missed connections", "Help with extra costs when a covered delay disrupts your trip."),
    ("suitcase-rolling", "Lost or delayed baggage", "Help with essentials and lost items, up to your plan's limits."),
   ],
   "faq": [
    {"q": "What does travel insurance cover?", "a": "Depending on the plan, coverage can include emergency medical care, trip cancellation and interruption, delays, and lost or delayed baggage. Each plan has its own benefits, limits, and exclusions, and I help you compare them for your trip."},
    {"q": "Who is eligible?", "a": "Eligibility depends on the plan and on your country of residence, destination, ages, and trip dates. The quote form asks for those so I can check your options."},
    {"q": "Which company provides the plan?", "a": "My travel plans come through Best Travel Assistance. Before you buy, I share the plan documents, which name the company that provides your coverage and pays claims."},
   ],
  },
  "es": {
   "eyebrow": "Seguro de viaje",
   "h1": "Seguro <em>para tu próximo viaje.</em>",
   "sub": "Cuéntame quiénes viajan y a dónde. Te envío opciones de planes según tu viaje y presupuesto.",
   "cov_h2": "Lo que puede cubrir un seguro de viaje",
   "items": [
    ("first-aid-kit", "Atención médica de emergencia", "Ayuda con gastos médicos si te enfermas o te lesionas durante tu viaje."),
    ("calendar-x", "Cancelación de viaje", "Reembolso de gastos prepagados si una causa cubierta te impide viajar."),
    ("clock-countdown", "Demoras y conexiones perdidas", "Ayuda con gastos extra cuando una demora cubierta afecta tu viaje."),
    ("suitcase-rolling", "Equipaje perdido o demorado", "Ayuda con artículos básicos y pertenencias perdidas, hasta los límites de tu plan."),
   ],
   "faq": [
    {"q": "¿Qué cubre el seguro de viaje?", "a": "Según el plan, la cobertura puede incluir atención médica de emergencia, cancelación e interrupción del viaje, demoras y equipaje perdido o demorado. Cada plan tiene sus propios beneficios, límites y exclusiones, y te ayudo a compararlos para tu viaje."},
    {"q": "¿Quién puede contratarlo?", "a": "La elegibilidad depende del plan y de tu país de residencia, destino, edades y fechas del viaje. El formulario pide esos datos para revisar tus opciones."},
    {"q": "¿Qué compañía provee el plan?", "a": "Mis planes de viaje vienen de Best Travel Assistance. Antes de comprar, te comparto los documentos del plan, que indican la compañía que provee tu cobertura y paga los reclamos."},
   ],
  },
 },
 "business": {
  "meta": {
   "en": ("Business Insurance Quotes in English and Spanish | AMP Insurance Assistance",
          "Quote general liability, commercial property, commercial auto, and workers' comp for your small business, with help in English and Spanish."),
   "es": ("Cotiza el seguro de tu negocio en español | AMP Insurance Assistance",
          "Cotiza responsabilidad civil, propiedad comercial, auto comercial y compensación laboral para tu negocio, con atención en español."),
  },
  "en": {
   "eyebrow": "Business insurance",
   "h1": "Insurance for <em>your small business.</em>",
   "sub": "Liability, property, commercial auto, and workers' comp. Tell me about your business and get options on WhatsApp.",
   "cov_h2": "What business insurance can cover",
   "items": [
    ("shield-check", "General liability", "Covers injuries and property damage your business causes to customers and others."),
    ("storefront", "Commercial property", "Protects your building, equipment, and inventory."),
    ("truck", "Commercial auto", "Covers the vehicles you use for work."),
    ("first-aid-kit", "Workers' compensation", "Pays medical costs and lost wages when an employee gets hurt on the job."),
    ("briefcase", "Professional liability", "Covers claims that your advice or service caused a client a financial loss."),
    ("package", "Business owner's policy", "Combines liability and property coverage in one policy for many small businesses."),
   ],
   "faq": [
    {"q": "Do I need workers' comp in Florida?", "a": "Florida requires it for most non-construction businesses with four or more employees, and for construction businesses with one or more employees. Different rules apply to farms."},
    {"q": "What do you need to quote my business?", "a": "The business name, what it does, its ZIP code, and your name. Years in business and the number of employees help too."},
    {"q": "Do I need general liability?", "a": "Many landlords, clients, and contracts require it. Send me the requirement and we will match the quote to it."},
   ],
  },
  "es": {
   "eyebrow": "Seguro para negocios",
   "h1": "Seguros para <em>tu pequeño negocio.</em>",
   "sub": "Responsabilidad civil, propiedad, autos comerciales y compensación laboral. Cuéntame de tu negocio y recibe opciones por WhatsApp.",
   "cov_h2": "Lo que puede cubrir un seguro de negocio",
   "items": [
    ("shield-check", "Responsabilidad civil general", "Cubre lesiones y daños a la propiedad que tu negocio cause a clientes y otras personas."),
    ("storefront", "Propiedad comercial", "Protege tu local, tus equipos y tu inventario."),
    ("truck", "Auto comercial", "Cubre los vehículos que usas para trabajar."),
    ("first-aid-kit", "Compensación laboral", "Paga gastos médicos y salarios perdidos cuando un empleado se lesiona en el trabajo."),
    ("briefcase", "Responsabilidad profesional", "Cubre reclamos de que tu asesoría o servicio le causó una pérdida económica a un cliente."),
    ("package", "Póliza para dueños de negocio (BOP)", "Combina responsabilidad civil y propiedad en una sola póliza para muchos pequeños negocios."),
   ],
   "faq": [
    {"q": "¿Necesito compensación laboral en Florida?", "a": "Florida la exige para la mayoría de los negocios fuera de la construcción con cuatro o más empleados, y para negocios de construcción con uno o más empleados. Hay reglas distintas para fincas agrícolas."},
    {"q": "¿Qué necesitas para cotizar mi negocio?", "a": "El nombre del negocio, a qué se dedica, su código postal y tu nombre. Los años en operación y el número de empleados también ayudan."},
    {"q": "¿Necesito responsabilidad civil general?", "a": "Muchos dueños de locales, clientes y contratos la exigen. Envíame el requisito y ajustamos la cotización a él."},
   ],
  },
 },
}

PAGE_GREETING = {
 "auto": {"en": "Hi Ana! I would like an auto insurance quote.", "es": "¡Hola Ana! Me gustaría una cotización de seguro de auto."},
 "home": {"en": "Hi Ana! I would like a home insurance quote.", "es": "¡Hola Ana! Me gustaría una cotización de seguro de hogar."},
 "renters": {"en": "Hi Ana! I would like a renters insurance quote.", "es": "¡Hola Ana! Me gustaría una cotización de seguro de inquilinos."},
 "travel": {"en": "Hi Ana! I would like a travel insurance quote.", "es": "¡Hola Ana! Me gustaría una cotización de seguro de viaje."},
 "business": {"en": "Hi Ana! I would like a business insurance quote.", "es": "¡Hola Ana! Me gustaría una cotización de seguro para mi negocio."},
}
